[project]
name = "crazy-treyn-blog"
version = "0.1.0"
description = "A Data Analytics blog for Crazy Treyn."
authors = [
  { name = "Trey", email = "your-email@example.com" }
]
dependencies = []

[tool.marimo.display]
theme = "dark"
cell_output = "below"